# Generated by Django 6.0.6 on 2026-06-21 12:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PdfTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('start_page', models.IntegerField(verbose_name='起始页码')),
                ('end_page', models.IntegerField(verbose_name='结束页码')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('status', models.CharField(default='success', max_length=30, verbose_name='处理状态')),
            ],
            options={
                'verbose_name': 'PDF拆分记录',
                'verbose_name_plural': 'PDF拆分记录',
            },
        ),
    ]
